package me.xiaoying.serverbuild.common;

public class ConfigCommon {
    public static boolean SETTING_BSTATS;

    public static String SETTING_DATA_TYPE,
            SETTING_DATA_SQLITE_DATAPATH,
            SETTING_DATA_MYSQL_HOST,
            SETTING_DATA_MYSQL_DATABASE,
            SETTING_DATA_MYSQL_USERNAME,
            SETTING_DATA_MYSQL_PASSWORD;
    public static int SETTING_DATA_MYSQL_PORT;

    public static String SETTING_COMMAND_MAIN,
            SETTING_COMMAND_USAGE_PARAMETER,
            SETTING_COMMAND_USAGE_MISSING_PARAMETER,
            SETTING_COMMAND_PARAMETER_DEFAULT,
            SETTING_COMMAND_PARAMETER_MISSING,
            SETTING_COMMAND_PARAMETER_INFINITY,
            SETTING_COMMAND_MISSING_DESCRIPTION;

    public static boolean OVERALL_SITUATION_ENABLE,
            OVERALL_SITUATION_VARIABLE_ENABLE,
            OVERALL_SITUATION_MESSAGE_ENABLE;
    public static String OVERALL_SITUATION_VARIABLE_DATEFORAMT,
            OVERALL_SITUATION_VARIABLE_PREFIX,
            OVERALL_SITUATION_MESSAGE_RELOAD,
            OVERALL_SITUATION_MESSAGE_COMPLETE,
            OVERALL_SITUATION_MESSAGE_MISSING_PERMISSION,
            OVERALL_SITUATION_MESSAGE_NEED_PLAYER,
            OVERALL_SITUATION_MESSAGE_MODULE_NOT_FOUND,
            OVERALL_SITUATION_MESSAGE_MODULE_OPENED,
            OVERALL_SITUATION_MESSAGE_MODULE_CLOSED,
            OVERALL_SITUATION_MESSAGE_MODULE_OPEN,
            OVERALL_SITUATION_MESSAGE_MODULE_CLOSE,
            OVERALL_SITUATION_MESSAGE_MODULE_INFO,
            OVERALL_SITUATION_MESSAGE_HELP;
}