name: ServerBuild
version: 0.0.2
main: me.xiaoying.sb.ServerBuild
softdepend:
  - PlaceholderAPI
authors: [筱樱, Tom, 清辰, LoveBukkitPlugin]
commands:
  sb:
    description: 全局命令
    permission: sb.admin
    aliases: [serverbuild]
  nb:
    description: (NotBuild) 管理员指令
    permission:  sb.nb.admin
    aliases: [notbuild]
  ltp:
    description: (LoginTP) 管理员指令
    permission: sb.lt.admin
    aliases: [logintp]
  tpa:
    description: (Teleport) 管理员指令
    permission: sb.tp.tpa
    aliases: [teleport]
  wm:
    description: (WelcomeMessage) 管理员指令
    permission: sb.wm.admin
    aliases: [welcomemessage]
  ars:
    description: (AutoReSpawn) 管理员指令
    permission: sb.wm.admin
    aliases: [autorespawn]
  home:
    description: (Home) 家
    permission: sb.home
  sethome:
    description: (Home) 设置家
    permission: sb.home.sethome
  delhome:
    description: (Home) 删除家
    permission: sb.home.delhome
permissions:
  sb.admin:
    description: 全局管理权限
    default: op
  sb.lt.admin:
    description: (LoginTP) 管理员权限
    default: op
  sb.tp.tpa:
    description: (Teleport) 管理员权限
    default: op
  sb.ars.admin:
    description: (AutoReSpawn) 管理员权限
    default: op
  sb.wm.admin:
    description: (WelcomeMessage) 管理员权限
    default: op
  sb.fm.admin:
    description: (FileMonitor) 管理员权限
    default: op