name: ServerBuild
version: 0.0.2
main: me.xiaoying.sb.ServerBuild
author: 筱樱
commands:
  sb:
    description: 全局命令
    permission: sb.admin
    aliases: [serverbuild]
  nb:
    description: (NotBuild) 管理员指令
    permission:  sb.nb.admin
    aliases: [notbuild]
  ltp:
    description: (LoginTP) 管理员指令
    permission: sb.lt.admin
    aliases: [logintp]
  tpa:
    description: (Teleport) 使用权限-传送
    permission: se.tp.tpa
    aliases: [teleport]
  wm:
    description: (WelcomeMessage) 使用权限-传送
    permission: se.wm.admin
    aliases: [welcomemessage]
permissions:
  sb.admin:
    description: 全局管理权限
    default: op
  sb.lt.admin:
    description: (LoginTP) 管理员权限
    default: op
  sb.tp.tpa:
    description: (Teleport) 使用权限-传送
    default: op
  sb.wm.admin:
    description: (WelcomeMessage) 管理员权限
    default: op