#插件基本配置

#设置
Setting:
  #统计插件使用情况，不进行任何数据操作
  Bstats: true
  #数据
  Data:
    #存储方式 (MYSQL/SQLite)
    Type: "SQLite"
    #SQLite 设置
    SQLite:
      #文件位置
      DataPath: "plugins/ServerBuild/ServerBuild.db"
    #Mysql 设置
    Mysql:
      #地址
      Host: "localhost"
      #端口
      Port: 3306
      #数据库
      Database: "serverbuild"
      #账户
      UserName: "root"
      #密码
      Password: "root"
  #默认 Command 帮助模板
  Command:
    #主题模板
    Main: |-
      
      &c! [帮助信息]
      &c|- &b%command% &8-> &a%description%
         &8├─ &6Alias: &e%command_aliases%
         &8└─ &6Usage: 
      %command_usage%
      &r
    #子命令帮助
    Usage:
      #当命令存在传递参数时显示的内容
      Parameter: |-
        \r\r\r\r\r\r\r\r\r\r&8├─ &b/%command% &7%parameter% &8-> &a%description%
      #当命令不存在传递参数时显示的内容
      MissingParameter: |-
        \r\r\r\r\r\r\r\r\r\r&8├─ &b/%command% &8-> &a%description%
    #当命令没有描述当前参数应该填写什么或是什么类型的时候应该实体用这个代替
    Parameter:
      #正常的命令传参提示
      Default: "< %parameter% >"
      #当命令没有配置对应的传递参数则应该显示内容
      Missing: "< %amount% 个参数>"
      #当命令设置的传递参数需要无限个时显示内容
      Infinity: "< Infinity 个参数>"
    #当没有描述的时候应该显示什么
    MissingDescription: "无描述"

#全局配置
OverallSituation:
  #总开关
  Enable: false
  #变量
  Variable:
    #开关
    Enable: false
    #日期格式(%date%)
    DateFormat: "yyyy/MM/dd-HH:mm:ss"
    #前缀(%prefix%)
    Prefix: "&a[&bServerBuild&a]&e>> "
  #词条
  Message:
    #开关
    Enable: false
    #重载
    Reload: "%prefix%&a重载完成！"
    #操作完成
    Complete: "%prefix%&a执行完成!"
    #无权限提示
    MissingPermission: "%prefix%&c没有权限这么做！"
    #需要以玩家身份执行
    NeedPlayer: "%prefix%&c请以玩家身份执行"
    #找不到 Module
    ModuleNotFound: "%prefix%&c找不到 Module&e(%module%)"
    #Module已是开启状态
    ModuleOpened: "%prefix%&e%module% &c已是开启状态"
    #Module 已是关闭状态
    ModuleClosed: "%prefix%&e%module% &c已是关闭状态"
    #开启 Module
    ModuleOpen: "%prefix%&e%module% &a已开启"
    #关闭 Module
    ModuleClose: "%prefix%&e%module% &6已关闭"
    #查询 Module 信息
    ModuleInfo: |
      
      &c&l！&6&l查询Module>> &b%module%(%module_exact%)
        &7|- &e状态: &a%module_state_enable%
        &7|- &e配置文件开启: &a%module_state_ready%
        &7|- &e作者: &a%module_info_author%
        &7|- &e版本: &a%module_info_version%
        &r